sky:
  datasource:
    #数据库设置
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: Alter1522
  #阿里云设置
  alioss:
    access-key-id:
    endpoint:
    access-key-secret:
    bucket-name:
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
  wechat:
    appid: wx66e9c32140e1819c
    secret: 4d2fd4c67cfe9950403662d1f5265588
